<a href="https://colab.research.google.com/github/MP-15/AGRITECH_Project/blob/main/District_Amritsar_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


# reading the database
data = pd.read_csv("/content/drive/MyDrive/Amritsar - Sheet1.csv")

# printing the top 10 rows
display(data.head(10))

,State Name,District Name,Market Name,Variety,Group,Arrivals (Tonnes),Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Reported Date
0,Punjab,Amritsar,Attari,Other,Cereals,1190,2125,2125,2125,15 May 2023
1,Punjab,Amritsar,Attari,Other,Cereals,560,2125,2125,2125,14 May 2023
2,Punjab,Amritsar,Attari,Other,Cereals,28,2125,2125,2125,13 May 2023
3,Punjab,Amritsar,Attari,Other,Cereals,52,2125,2125,2125,12 May 2023
4,Punjab,Amritsar,Attari,Other,Cereals,220,2125,2125,2125,10 May 2023
5,Punjab,Amritsar,Attari,Other,Cereals,675,2125,2125,2125,09 May 2023
6,Punjab,Amritsar,Attari,Other,Cereals,112,2125,2125,2125,08 May 2023
7,Punjab,Amritsar,Attari,Other,Cereals,140,2125,2125,2125,07 May 2023
8,Punjab,Amritsar,Attari,Other,Cereals,1135,2125,2125,2125,01 May 2023
9,Punjab,Amritsar,Attari,Other,Cereals,1310,2125,2125,2125,30 Apr 2023

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
data.shape

(320, 10)

In [4]:
df1['A'].plot.hist(bins=50)

NameError: name 'df1' is not defined